server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        # 👇 FIX: Point to the Docker Service Name defined in docker-compose.yml
        proxy_pass http://bookstore-backend:8080;
        proxy_set_header Host $host;
    }
}