spring.application.name=Bookstore
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=bookstore_user
spring.datasource.password=bookstore_pass
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
# We manage schema & triggers manually in SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace